### PR TITLE
Add sync between seek bar and chapter control buttons

### PR DESCRIPTION
**Pull request by jonasburian**
For AntennaPod#5075
This is a one way sync from the buttons to the seek bar. Maybe we want to do this the other way around too? (But in my experience, the asynchronicity is not such a problem there)

### CODE REVIEW

**Comment by ByteHamster** [comment]
Hmm. This couples the fragments more among each other. How about changing PlaybackService, so that it immediately sends a position update event after seeking? Then the fragments should be able to handle the changes themselves.

**Comment by ueen** [comment]
Hmm ok, @jonasburian tbh i dont even know what issue this is fixing, can you send a video or smth? :D

**Comment by jonasburian** [comment]
> can you send a video or smth?

Here is how it looks like:
https://user-images.githubusercontent.com/15125616/117348030-06ff4c80-aeaa-11eb-972f-fe357c600985.mp4
The proper behavior should be, that the seek bar seeks to the beginning of the chapter and highlights it.

> How about changing PlaybackService

I'll look into it

**Comment by jonasburian** [comment]
Looks like it didn't even got updated before :D (wasn't necessary before)

**Comment by ueen** [comment]
can you add that code in this PR then i'll just merge?

**Comment by jonasburian** [comment]
Tested a few things. I think calling it in updateUi is not frequent enough. Looked into PlaybackService too, but the time gets updated as soon as you seek. So I think that this PR is already okay as it is :)

**Pull request merged**
